theme: jekyll-theme-leap-day
title: Ashish Workbench
email: meetashishpardeshi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Site Description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ashishworkbench.github.io" # the base hostname & protocol for your site
twitter_username: PardeshiAshishK
github_username:  ashishworkbench
